version: "3.5"

services:
  expressvpn:
    container_name: privoxy-tor-expressvpn
    image: polkaned/privoxy-tor-expressvpn:latest
    privileged: true
    restart: always
    environment:
      - ACTIVATION_CODE={% your-activation-code %}
      - SERVER={% LOCATION/ALIAS/COUNTRY %}
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - 9050:9050
      - 9052:9052
      - 8118:8118
    tty: true
    stdin_open: true
    command: /bin/bash
